-- Cria a tabela de subcategorias/modalidades por projeto.
-- Nota: projeto_id é um inteiro sem FK para tabela de projetos, pois o schema
-- do Supabase não possui tabela separada de projetos. O mapeamento
-- (1=Adolescer, 2=Criança Certeza, 3=Sempre Criança, 4=Valorizando,
-- 5=Clube de Mães, 6=Animar) é mantido no frontend.

CREATE TABLE IF NOT EXISTS public.subcategorias (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id  integer NOT NULL,
    nome        text    NOT NULL,
    ativo       boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_subcategorias_projeto_nome UNIQUE (projeto_id, nome)
);

CREATE INDEX IF NOT EXISTS idx_subcategorias_projeto_id
    ON public.subcategorias (projeto_id);

COMMENT ON TABLE public.subcategorias IS
    'Subcategorias/modalidades de cada projeto. projeto_id é numérico (sem tabela projetos no Supabase).';

-- Seed idempotente usando ON CONFLICT DO NOTHING
-- Adolescer (projeto_id = 1)
INSERT INTO public.subcategorias (projeto_id, nome) VALUES
    (1, 'Ballet'),
    (1, 'Capoeira'),
    (1, 'Esporte'),
    -- Criança Certeza (projeto_id = 2)
    (2, 'Ballet'),
    (2, 'Capoeira'),
    (2, 'Esporte'),
    -- Sempre Criança (projeto_id = 3)
    (3, 'Ballet'),
    (3, 'Capoeira'),
    (3, 'Esporte'),
    -- Valorizando (projeto_id = 4)
    (4, 'Ballet'),
    (4, 'Capoeira'),
    (4, 'Esporte')
ON CONFLICT (projeto_id, nome) DO NOTHING;
